package me.xalgorhythms.mobbosses;

import me.xalgorhythms.mobbosses.Commands.MobBossesCommand;
import me.xalgorhythms.mobbosses.Files.BossList;
import me.xalgorhythms.mobbosses.Files.RegionMapStorage;
import me.xalgorhythms.mobbosses.Files.Regions;
import me.xalgorhythms.mobbosses.BossRegions.BossRegion;
import me.xalgorhythms.mobbosses.Listeners.PlayerInRegion;
import org.bukkit.Bukkit;
import org.bukkit.plugin.java.JavaPlugin;

public final class Main extends JavaPlugin {

	@Override
	public void onEnable() {
		// Plugin startup logic

		getLogger().info("The plugin is loading now...");

		getConfig().options().copyDefaults();
		saveDefaultConfig();

		/*BossList.setup();
		BossList.get().addDefault("BossList", "This file is not yet ready for use. Do not edit this file.");
		BossList.get().options().copyDefaults(true);
		BossList.save();*/

		Regions.setup();
		Regions.get().addDefault("Warning", "EDITING THIS FILE MAY BREAK THE PLUGIN. EDIT AT YOUR OWN RISK.");
		Regions.get().options().copyDefaults(true);
		Regions.save();
		getLogger().info("Regions loaded successfully");

		//RegionMapStorage.load();
		//getLogger().info("Successfully deserialized regionMap storage");

		Bukkit.getPluginManager().registerEvents(new PlayerInRegion(), this);
		getCommand("mobbosses").setExecutor(new MobBossesCommand());

		getLogger().info("The plugin has loaded successfully!");

	}

	@Override
	public void onDisable() {
		// Plugin shutdown logic

		Regions.save();

		//RegionMapStorage.save();
	}
}
